feat: leave server name and lets encrypt email as variables

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,17 @@ stages:
 before_script:
   - apk add rsync openssh curl
   - cp $CI_ENV ${CI_PROJECT_DIR}/.env.production
+  - |
+      if [ -z "$CI_SERVER_NAME" ]; then
+        echo "CI_SERVER_NAME variable is not set. Pipeline failed."
+        exit 1
+      fi
+  - |
+      if [ -z "$CI_LETSENCRYPT_EMAIL" ]; then
+        echo "CI_LETSENCRYPT_EMAIL variable is not set. Pipeline failed."
+        exit 1
+      fi
+  - sed -i "s/server_name: \$CI_SERVER_NAME/server_name: $CI_SERVER_NAME/" ${CI_PROJECT_DIR}/nginx.conf
   - mkdir -p ${CI_PROJECT_DIR}/elasticsearch-certs
   - cp $CI_SSL_KEY ${CI_PROJECT_DIR}/elasticsearch-certs/admin-key.pem
   - cp $CI_SSL_CERT ${CI_PROJECT_DIR}/elasticsearch-certs/admin.pem
